### ISSUE TITLE
list from "Add Darwin Core terms" button may need a bit of clean up

### ISSUE THREAD

**Issue by ymgan** [SIOS-Svalbard/Nansen_Legacy_template_generator#66]
Darwin Core classes and controlled vocabulary values (e.g. values for basisOfRecord) should perhaps be removed from the list in Add Darwin Core terms:

![Screenshot 2024-07-30 at 11 25 18](https://github.com/user-attachments/assets/8d7ddf51-8437-486c-af5b-b4cf09617098)

I also think if user selected for Event Core, maybe it is a good idea to restricts the list from "Add Darwin Core terms" to only allow terms from Event Core (excluding Occurrence Core term)

Thanks a lot!

**Comment by lhmarsden** [comment]
This was trickier than I thought it should be because of how this source file:
https://github.com/tdwg/rs.tdwg.org/blob/master/terms/terms.csv

I see no obvious way to extract only Darwin Core terms that can be used as column headers. This seems to include a range of different things...

I am trying to fix this by excluding rows where the term begins with a capital:
```
df = df[~df['term_localName'].str.match(r'^[A-Z]')]
```

I think this should catch most things... I am reluctant to do a lot of hardcoding which will take time to develop and maintain.

**Comment by lhmarsden** [comment]
Regarding your second point, I discussed this with GBIF Norway during development. Some scientists prefer to begin with everything in one table whilst they are recording/collecting/preparing their data. They can map to several cores/extensions later. This button allows scientists to keep this flexibility. I could however call it something different like 'Darwin core terms not in core/extension'...?

**Comment by lhmarsden** [comment]
![image](https://github.com/user-attachments/assets/355ee31e-cab4-40e2-8004-5b24e48ec98d)
I hope this addresses this issue sufficiently. Feel free to reopen if not.

**Comment by ymgan** [comment]
Thank you so much for working on this @lhmarsden !! I just got back from vacation!
What you mentioned made a lot of sense, thank you for being thoughtful! This is perfect!!

**Comment by lhmarsden** [comment]
The latest version has now been pulled to https://www.nordatanet.no/aen/template-generator/ @ymgan
