### ISSUE TITLE
Add option for OBIS-required terms

### ISSUE THREAD

**Issue by EliLawrence** [SIOS-Svalbard/Nansen_Legacy_template_generator#68]
I thought it might be interesting to include a button that will check off the Darwin Core terms required for the OBIS community since it differs somewhat (https://manual.obis.org/darwin_core.html#darwin-core-dwc-terms). We've been including the link to this generator in various places but always have to caution our users that OBIS required terms aren't checked by default.

If this is outside the scope of the generator then that's okay! Thank you

**Comment by lhmarsden** [comment]
Hi @EliLawrence, yes this is a good suggestion. I will try to get round to doing this at some point and will comment here when this is done.

**Comment by lhmarsden** [comment]
Hi @EliLawrence I will be shortly changing all the requirements and recommendations to match the OBIS requirements for the occurrence core, exntension and event core.

I hope this is suitable. This was much quicker to implement than a GBIF/OBIS button. But I think the OBIS requirements encompass all of the GBIF requirements, just adding a few extra terms. Since the template generator is aimed at scientists mostly, and since Nansen Legacy was a marine project, I think it makes sense to comply with OBIS in this case.

Generally speaking, I am more than happy to comply with more restrictive requirements. 

If you feel this doesn't resolve your query, feel free to re-open the issue once I close it.

**Comment by lhmarsden** [comment]
The new version is now available online.

**Comment by EliLawrence** [comment]
Looks good Luke! I think it resolves the request. I'll open a new issue if I notice anything missing but first glance it seems okay. Thank you!
